### ISSUE TITLE
error: Invalid checksum of length 2043 expected 32

### ISSUE THREAD

**Issue by sadegh-q** [Epic-R-R/Geph-linux#1]

**Comment by hshaterian** [comment]
same here ...
after command:

$ curl -o Geph-x86_64.flatpak -L https://3.ly/aocQL && flatpak install Geph-x86_64.flatpak

there will be error:
error: Invalid checksum of length 2043 expected 32

**Comment by Epic-R-R** [comment]
This error occurs when the file is corrupted
The file has been updated, you can try again

**Comment by alishah79** [comment]
I still have this problem. My os is lubuntu 18.

**Comment by tourdotted** [comment]
hello sir please give us unshrunken url or update link please

**Comment by Epic-R-R** [comment]
Hello,
The file has been updated, now you can use the file inside the repo for installation

**Comment by Epic-R-R** [comment]
> Hello, The file has been updated, now you can use the file inside the repository for installation

Link updated
