### ISSUE TITLE
Invalid checksum of length 2043 expected 32

### ISSUE THREAD

**Issue by AlirezaBahadoriZadeh2002** [Epic-R-R/Geph-linux#2]
Hello
I have an error in this part
curl -o Geph-x86_64.flatpak -L https://3.ly/asvh5 && flatpak install Geph-x86_64.flatpak
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  CurrentDload  Upload   Total   Spent    Left  Speed
100   291  100   291    0     0    829      0 --:--:-- --:--:-- --:--:--   829
100   162  100   162    0     0    252      0 --:--:-- --:--:-- --:--:--   252
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 62077    0 62077    0     0  38461      0 --:--:--  0:00:01 --:--:-- 38461
error: Invalid checksum of length 2043 expected 32

**Comment by Epic-R-R** [comment]
Hi,
Thanks for the report,
File updated!
