### ISSUE TITLE
share yml file

### ISSUE THREAD

**Issue by mohammadRezaeian** [Epic-R-R/Geph-linux#3]
hi thanks for create this package
could you please share yml file Geph-x86_64.flatpak ?

**Comment by Epic-R-R** [comment]
Hi, unfortunately, I do not have the YML file for Geph

**Comment by mohammadRezaeian** [comment]
Sorry, but if you do not have the YML file
how can you create a Flatpak package for installing?
( CUZ i know before install a package we must use yml file for create binary file flatpak package )

**Comment by Epic-R-R** [comment]
I downloaded files from the official website, some users can't download them because they don't have a VPN so I downloaded and put files here so users can download them easily
